apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: vaidhi/simple-application:frontend1
        name: simple-application
        env:
          - name: NEXT_PUBLIC_API_URL
            value: http://backend-service.backend.svc:8000
        resources: {}
      serviceAccountName: frontend

