apiVersion: v1
imagePullSecrets:
- name: docker-cred
kind: ServiceAccount
metadata:
  name: frontend
  namespace: frontend

---

apiVersion: v1
imagePullSecrets:
- name: docker-cred
kind: ServiceAccount
metadata:
  name: backend
  namespace: backend

